sudo: false
language: node_js
branches:
  only:
  - master
  - dev
node_js:
- 6.10.2
install:
- npm install
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: BP2Ny0hDnP9T/Eu77k7XomuBLY+yJqmesgS+0qZSI+fcaHWGbcvm9pMuep6DiZ+C8H0n33O2PXL3qbEw3K1g8uI1lDxgQ6Prqrha1akIrQP0SEHD5A6/bgCP89LDo4bVEdWHY2Cek9adRU/4Exxw6h0a+RWV7XZyhXivQh8A6xJepxzR+5BPj+UOS88Qp3tEUUyKNHbhA/6fpz4rR+Myq3zfy3hVTpQLs3Ssn0rWw7I1SOdDOZ65zJoG2aCQ8l2S+x1kjWoJxhcJ5Njn1b2c81+SFAlD07Nk+lNDBe4fnV+NTPHasDUyZal40LdTUGCKt4La3TKCZRDLGEK+I5g9EpR+EaV+RsLXHrp6cFY8jJW1lNi1d2/42rEchjtEQyPPbifg2kfm+aKbEEMePE2W6gIAQuqdMgKfFw5R/UaWs9twQjHAxaA+Cn29DvTZvFK57mv1yoJowmblBtl4QoDGGMCscyON49lhezOIEvnV7QgrP6N848I4JAZQLvk9wpOQZkm8+gKoXVb7ehTRElxn0Oeir2jKjvkDZF5IODGEGucfWLx6tvfXxkM4w3kRhWE/QAVUeXG4kPKBmfp6leg5hzFcXv2H+HrRpbPNfVDpRDQt5bjzxxtSbFRByzebucypAJr0En8Pa153Hfw/K0hC54oBrWEjCWe455at0qpjJm8=
  app:
    master: lunchfinder-api
cache:
  directories:
  - node_modules
